### ISSUE TITLE
Can't get setup.py to run on Py 3.8

### ISSUE THREAD

**Issue by peircej** [marcus-nystrom/Titta#25]
At the moment, under Python 3.8 the package refuses to install with
```
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    long_description=open('README.md').read(),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 401: invalid start byte
```

It seems not to like the ö in Nyström

**Comment by marcus-nystrom** [comment]
Removed the 'ö'. Hope that does the trick.
